#pragma once

// Dependencies | GLFW
#include <GLFW/glfw3.h>

enum class GLFWJoystickButtonCode {
	UNKNOWN =		-1,
	A =				GLFW_GAMEPAD_BUTTON_A,
	B =				GLFW_GAMEPAD_BUTTON_B,
	X =				GLFW_GAMEPAD_BUTTON_X,
	Y =				GLFW_GAMEPAD_BUTTON_Y,
	LEFT_BUMPER =	GLFW_GAMEPAD_BUTTON_LEFT_BUMPER,
	RIGHT_BUMPER =	GLFW_GAMEPAD_BUTTON_RIGHT_BUMPER,
	BACK =			GLFW_GAMEPAD_BUTTON_BACK,
	START =			GLFW_GAMEPAD_BUTTON_START,
	//GUIDE =			GLFW_GAMEPAD_BUTTON_GUIDE,
	LEFT_THUMB =	GLFW_GAMEPAD_BUTTON_LEFT_THUMB - 1,
	RIGHT_THUMB =	GLFW_GAMEPAD_BUTTON_RIGHT_THUMB - 1,
	DPAD_UP =		GLFW_GAMEPAD_BUTTON_DPAD_UP - 1,
	DPAD_RIGHT =	GLFW_GAMEPAD_BUTTON_DPAD_RIGHT - 1,
	DPAD_DOWN =		GLFW_GAMEPAD_BUTTON_DPAD_DOWN - 1,
	DPAD_LEFT =		GLFW_GAMEPAD_BUTTON_DPAD_LEFT - 1
};
