#pragma once

// Dependencies | GLFW
#include <GLFW/glfw3.h>

enum class GLFWMouseButtonCode {
	UNKNOWN = -1,
	BUTTON_CODE_1 = GLFW_MOUSE_BUTTON_1,
	BUTTON_CODE_2 = GLFW_MOUSE_BUTTON_2,
	BUTTON_CODE_3 = GLFW_MOUSE_BUTTON_3,
	BUTTON_CODE_4 = GLFW_MOUSE_BUTTON_4,
	BUTTON_CODE_5 = GLFW_MOUSE_BUTTON_5,
	BUTTON_CODE_6 = GLFW_MOUSE_BUTTON_6,
	BUTTON_CODE_7 = GLFW_MOUSE_BUTTON_7,
	BUTTON_CODE_8 = GLFW_MOUSE_BUTTON_8
};
