#pragma once

// Dependencies | GLFW
#include <GLFW/glfw3.h>

enum class GLFWJoystickAxisCode {
	UNKNOWN =		-1,
	LEFT_X =		GLFW_GAMEPAD_AXIS_LEFT_X,
	LEFT_Y =		GLFW_GAMEPAD_AXIS_LEFT_Y,
	RIGHT_X =		GLFW_GAMEPAD_AXIS_RIGHT_X,
	RIGHT_Y =		GLFW_GAMEPAD_AXIS_RIGHT_Y,
	LEFT_TRIGGER =	GLFW_GAMEPAD_AXIS_LEFT_TRIGGER,
	RIGHT_TRIGGER =	GLFW_GAMEPAD_AXIS_RIGHT_TRIGGER,
};
